In [2]:
import numpy as np
q_table=np.load("/data1/sunshuo/qml/HFT/HFT_04_11/q_table.npy")
q_table

array([[[ 0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00]],

       [[ 2.54125971e+01,  2.53997131e+01],
        [ 2.54125971e+01,  2.54435171e+01]],

       [[ 2.54201111e+01,  2.54380351e+01],
        [ 2.54201111e+01,  2.55180351e+01]],

       ...,

       [[ 0.00000000e+00, -4.05674320e-02],
        [ 0.00000000e+00,  4.04325680e-02]],

       [[ 0.00000000e+00, -1.27000000e-01],
        [-5.68000000e-04, -5.70000000e-02]],

       [[ 0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00]]])

In [3]:
import pandas as pd
data_path = "/data1/sunshuo/qml/HFT/HFT_04_11/data/small_df.feather"
df = pd.read_feather(data_path).iloc[0:10000]
df[df.timestamp==1674531919.0]

timestamp  bid1_price  bid1_size  bid2_price  bid2_size  bid3_price  \
647  1674531919    23050.42    0.00434    23050.41    0.00069    23050.29   

     bid3_size  bid4_price  bid4_size  bid5_price  ...  imxd_60_dis  \
647    0.00001     23050.0    0.00114    23049.98  ...            0   

     midpoint_diff_60  ask1_diff_60  bid1_diff_60  midpoint_trend_60  \
647          0.723687      0.937157      0.514036          -0.027252   

     ask1_price_trend_60  bid1_price_trend_60  buy_spread_oe_trend_60  \
647             0.171708            -0.217726                0.661536   

     sell_spread_oe_trend_60  imblance_volume_oe_trend_60  
647                -1.205765                    -1.805093  

[1 rows x 144 columns]

In [4]:
q_table[647]

array([[ 2.48157966e+01,  2.47420434e+01],
       [-1.00000000e+13,  2.48600434e+01]])

In [5]:
q_table

array([[[ 0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00]],

       [[ 2.54125971e+01,  2.53997131e+01],
        [ 2.54125971e+01,  2.54435171e+01]],

       [[ 2.54201111e+01,  2.54380351e+01],
        [ 2.54201111e+01,  2.55180351e+01]],

       ...,

       [[ 0.00000000e+00, -4.05674320e-02],
        [ 0.00000000e+00,  4.04325680e-02]],

       [[ 0.00000000e+00, -1.27000000e-01],
        [-5.68000000e-04, -5.70000000e-02]],

       [[ 0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00]]])

In [6]:
len(q_table)

7200

In [7]:
df.iloc[0:1]

timestamp  bid1_price  bid1_size  bid2_price  bid2_size  bid3_price  \
0  1674531272    23036.01    0.03551    23035.46    0.03551    23035.32   

   bid3_size  bid4_price  bid4_size  bid5_price  ...  imxd_60_dis  \
0    0.00103     23035.2    0.00066    23035.17  ...            1   

   midpoint_diff_60  ask1_diff_60  bid1_diff_60  midpoint_trend_60  \
0          1.385502      1.345592       1.42426           1.040322   

   ask1_price_trend_60  bid1_price_trend_60  buy_spread_oe_trend_60  \
0             1.028825             1.050455                1.754245   

   sell_spread_oe_trend_60  imblance_volume_oe_trend_60  
0                 0.816416                    -1.272423  

[1 rows x 144 columns]

In [9]:
df.iloc[0:1].shape

(1, 144)

In [11]:
(df.iloc[0:1].timestamp==1674531272).values.item()

True

In [18]:
import pandas as pd
import numpy as np
high_level_macro_action=np.load("/home/mlqin/qml/HFT_06_01/high_level_action_list.npy",allow_pickle=True)
low_level_macro_action=np.load("/home/mlqin/qml/HFT_06_01/low_level_action_list.npy",allow_pickle=True)
high_level_time=np.load("/home/mlqin/qml/HFT_06_01/high_level_timestamp_list.npy",allow_pickle=True)
low_level_time=np.load("/home/mlqin/qml/HFT_06_01/low_level_timestamp_list.npy",allow_pickle=True)
high_level_state=np.load("/home/mlqin/qml/HFT_06_01/high_level_state_list.npy",allow_pickle=True)
low_level_state=np.load("/home/mlqin/qml/HFT_06_01/low_level_state_list.npy",allow_pickle=True)

In [19]:
len(high_level_macro_action)

99999

In [20]:
len(low_level_macro_action)

99999

In [22]:
len(high_level_time)

99999

In [28]:
len(low_level_time)

99999

In [29]:
len(high_level_state)

99999

In [30]:
len(low_level_state)

99999

In [34]:
for i in range(len(high_level_state)):
    print(np.sum(high_level_state[i]==low_level_state[i]))

54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
5

In [35]:
len(np.load("/home/mlqin/qml/HFT_06_01/data/feature/second_feature.npy"))

54

In [37]:
whole=[]
for i in range(5):
    b=[]
    b.append(1)
    whole.append(b)
whole

[[1], [1], [1], [1], [1]]

In [1]:
a=[1,2,3,1,2,3,11]
sorted(a)

[1, 1, 2, 2, 3, 3, 11]

In [6]:
import pandas as pd
import numpy as np
data=pd.read_feather("/home/mlqin/qml/HFT_06_17/data/BTCTUSD/valid.feather")
data["imblance_volume_oe"]

0         0.604162
1         0.935188
2         0.921345
3         0.758983
4        -0.767742
            ...   
811423    0.155258
811424    0.876256
811425    0.857055
811426    0.772805
811427    0.515896
Name: imblance_volume_oe, Length: 811428, dtype: float64

In [7]:
data["imblance_volume_oe"].quantile(0.25)

-0.581198831850466

In [8]:
data["imblance_volume_oe"].quantile(0.5)

-0.04319816737758347

In [9]:
data["imblance_volume_oe"].quantile(0.75)

0.505790675900752

In [5]:
for feature in data.columns:
    if 'imblance_volume_oe' in feature:
        print(feature)

imblance_volume_oe
imblance_volume_oe_trend_5
imblance_volume_oe_diff_5
imblance_volume_oe_trend_10
imblance_volume_oe_diff_10
imblance_volume_oe_trend_30
imblance_volume_oe_diff_30
imblance_volume_oe_trend_60
imblance_volume_oe_diff_60
